language: ruby
rvm:
  - 2.4.1
before_install:
  - git clone https://code.googlesource.com/re2
  - cd re2
  - make
  - make test
  - sudo make install
  - sudo make testinstall
notifications:
  email: false
